# Site settings
title: "PartiCourts"
description: "Explore and analyze court data with PartiCourts"
author: "Mikael"
baseurl: "/DisplayMaps" # This is correct for deployment in a subdirectory
url: "https://Mikael-UofA.github.io"

# Jekyll build settings
source: ./DisplayMaps # Specify the source folder to restrict Jekyll to `DisplayMaps`
destination: ./_site # Output folder remains `_site`

# Markdown and content
markdown: kramdown
kramdown:
  input: GFM

# Plugins
plugins:
  - jekyll-seo-tag
